### ISSUE TITLE
Micro menu is empty when clicking on the settings icon at the bottom right of the screen

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI4#27]
Micro menu is empty when clicking on the settings icon at the bottom right of the screen. Also, the padding seems a bit big between the icon and the open menu:

![empty_micro_menu](https://user-images.githubusercontent.com/120369133/207119031-afd56195-9290-453a-8f4f-cb4623f9676c.png)

**Comment by anaarkei** [comment]
I hope the old menu makes a return, that and the main menu reskin, that styling was top notch.

**Comment by deftanksfault** [comment]
I use this one in the meantime, from Goldpaws as well: https://www.curseforge.com/wow/addons/biggamemenu

**Comment by Goldpaw** [comment]
Biggamemenu is for the escape menu, not the in-game panels. So that addon is unrelated.

However, the micro menu is fixed in both the wrath version (this) and the dragonflight version of the UI now.
