### ISSUE TITLE
Xp bar doesn't seem to be updated in real time

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI4#40]
I need to reload the UI for the xp bar (purple circle) to get updated.

**Comment by Goldpaw** [comment]
Not intentional at all. Clearly I broke something somewhere. Will look into it!

**Comment by Goldpaw** [comment]
This has been fixed for wrath classic in the latest update. 

Dragonflight now uses a different set of code and has its own issue tracker here: 
https://github.com/GoldpawsStuff/AzeriteUI5/issues

Note that the xp bar isn't implemented yet in the new (alpha tagged) dragonflight version.
