### ISSUE TITLE
Boss has a wooden unit frame

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI4#41]
I don't know if this bug is isolated or if all bosses (at level ??) have it, but I met Rukhmar in WoD who had a wooden unit frame:

![Screenshot 2022-12-16 154121](https://user-images.githubusercontent.com/120369133/208232153-a58561b8-3542-4827-94c5-bee146e372bf.png)

**Comment by Goldpaw** [comment]
No, lol, that's not supposed to happen. It's the exact opposite of what is supposed to happen. Wooden frames are for very low levels, usually before the player level where mounts can be ridden (not counting the motorcycles with passenger seats).

Clearly I messed up something here!

**Comment by deftanksfault** [comment]
Haha I know, what I don't know though is if it's an isolated issue (only some bosses, for some reasons) or all the bosses.

**Comment by Goldpaw** [comment]
it's bosses when you're character isn't max level. there's a flaw in the logic I used to decide the texture.

**Comment by deftanksfault** [comment]
Ah, right. Thanks for the explanation!
