### ISSUE TITLE
[Feature] <Historical version>

### ISSUE THREAD

**Issue by xuesemofa** [GoldpawsStuff/AzeriteUI4#46]
### Is this feature request for AzeriteUI for Wrath Classic?

- [X] Yes, I understand. This is for Wrath Classic.

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I hope to get the plug-ins corresponding to the 3.3.5 game version

### Describe the solution you'd like

I haven't found a plug-in with the game version 335 for a long time. I like the effect of this plug-in very much. If there is a place where I can download it, please let me know.

**Comment by Goldpaw** [comment]
Never has existed any AzeriteUI versions for private realms, never will. So sorry, can't help you with that one.
